#!/bin/bash
echo "REMOVE DIR for ARMITAGE"
rm -r /usr/share/armitage
echo "CD to downloads"
cd /root/Downloads
echo "DOWNLOADING ARMITAGE"
wget http://www.fastandeasyhacking.com/download/armitage150813.tgz
echo "UNPACKING ARMITAGE"
tar -xf armitage150813.tgz
echo "Delete Armitage.tgz"
rm -r armitage150813.tgz
echo "COPY ARMITAGE to /USR/SHARE/"
cp -r armitage /usr/share/armitage
echo "STARTING postgresql"
/etc/init.d/postgresql start
echo "FIX msfdb DB"
msfdb delete
msfdb start
msfdb init
echo "Ready to try ARMITAGE......"

