#!/bin/bash
cd /etc/apt
echo "STARTING TO FIX ALL KALIs BAD FILE COUNFIGs...yeah..."
#----------------Fix REPOS--------------------------------
echo "Fixing Source lists"
echo " ">sources.list
echo "deb http://http.kali.org/kali sana main non-free contrib">>sources.list
echo "deb http://security.kali.org/kali-security sana/updates main contrib non-free">>sources.list
echo "deb-src http://http.kali.org/kali sana main non-free contrib">>sources.list
echo "deb-src http://security.kali.org/kali-security sana/updates main contrib non-free">>sources.list
echo "To add the rolling repos copy them from script and uncomment them and then paste in terminal"
#echo "deb http://http.kali.org/kali kali-rolling main contrib non-free">>sources.list
#echo "deb http://security.kali.org/kali-security kali-rolling/updates main contrib non-free">>sources.list
echo "FIXED THE REPO SOURCE.LIST. Your Welcome!"
#----------------Fix wireless Interface issue--------------------------------
echo "Fixing Wifi issue"
cd /etc/network/
echo "#Wireless Interface setup by install script"
echo "auto wlan0">>interfaces
echo "iface wlan0 inet manual">>interfaces
echo "#iface wlan0 inet static">>interfaces
echo "#wpa-ssid AP_NAME">>interfaces
echo "#wpa-key-mgmt WPA-PSK">>interfaces
echo "Fixed wireless config issue, might have to reboot to get it to work."
#----------------Fix Interface--------------------------------
echo"Starting to grab updates (BUT NOT UPGRADE DUE TO THE UPGRADES WILL BREAK ARMITAGE AT THIS TIME)"
cd /
apt-get update 
#apt-get upgrade -y
#apt-get dist-upgrade -y 
msfupdate
#----------------INSTALL REPOS--------------------------------
echo "Installing good packages to have"
apt-get install geany -y 
apt-get install mitmf -y
apt-get install fruitywifi -y
apt-get install veil-evasion -y
apt-get -y install bleachbit
apt-get -y install goldendict
apt-get -y install gtk-recordmydesktop
apt-get -y install pinta
apt-get -y install ibus && apt-get -y install ibus-unikey
apt-get -y install libreoffice
apt-get -y install knotes
apt-get -y install network-manager-gnome
apt-get -y install network-manager-openvpn
apt-get -y install network-manager-openvpn-gnome
apt-get -y install network-manager-pptp
apt-get -y install network-manager-pptp-gnome
apt-get -y install network-manager-strongswan
apt-get -y install network-manager-vpnc
apt-get -y install network-manager-vpnc-gnome
apt-get -y install unrar unace rar unrar p7zip zip unzip p7zip-full p7zip-rar file-roller
apt-get -y install gdebi &>/dev/nul
apt-get -y install deluge &>/dev/null
apt-get -y install python-elixir
apt-get -y install ldap-utils rwho rsh-client x11-apps finger
apt-get -y install nipper-ng jsql oclgausscrack ghost-phisher uniscan -y
apt-get -y install lbd automater arachni bully inguma sslsplit dumpzilla -y 
apt-get -y install owasp-mantra-ff recon-ng ridenum regripper jd-gui -y
apt-get -y install freerdp-x11 -y
apt-get -y install libssl-dev -y
apt-get -y install libpcap-dev -y
apt-get -y install libsqlite3-dev -y
apt-get -y install metagoofil
apt-get -y install passing-the-hash unicornscan winexe
apt-get -y install unicornscan enum4linux polenum 
apt-get -y install nfspy firmware-mod-kit wmis
apt-get -y install Beef
apt-get -y install veil-catapult
apt-get -y install unicornscan
apt-get -y install backdoor-factory
apt-get -y install shellter
apt-get -y install jboss-autopwn
apt-get -y install eyewitness
apt-get -y install wifite
#apt-get -y install set
apt-get -y install openvas
apt-get -y install guake
#-----------------------------START GETTING FROM GITHUB------------------------
echo "Getting clones from Github"
cd /root/Desktop
mkdir HackerTools
git clone https://github.com/CeramicSkate0/Kali-Scripts
git clone https://github.com/trustedsec/ptf
cd HackerTools
git clone https://github.com/CeramicSkate0/Wrapper-For-MITMF
git clone https://github.com/PowerShellEmpire/Empire
git clone https://github.com/PyroTek3/PowerShell-AD-Recon
git clone https://github.com/nidem/kerberoast
git clone https://github.com/michenriksen/gitrob
git clone https://github.com/byt3bl33d3r/gcat.git
git clone https://github.com/jekyc/wig.git 
git clone https://github.com/GDSSecurity/Windows-Exploit-Suggester.git 
git clone https://github.com/MarioVilas/shellcode_tools.git 
git clone https://github.com/dotcppfile/DAws.git 
git clone https://github.com/dotcppfile/Serbot.git 
git clone https://github.com/rfunix/Pompem.git 
git clone https://github.com/AlessandroZ/LaZagne.git 
git clone https://github.com/PenturaLabs/Linux_Exploit_Suggester.git 
git clone https://github.com/stasinopoulos/commix.git 
git clone https://github.com/0x90/bluetooth-arsenal
git clone https://github.com/rsmudge/cortana-scripts
#-------------------------------------------------------------------------------
wget https://github.com/Top-Hat-Sec/thsosrtl/blob/master/VeePeeNee/VeePeeNee.sh
mv VeePeeNee.sh vpnbook.sh
chmod a+x vpnbook.sh
#-------------------------------------------------------------------------------
git clone https://github.com/byt3bl33d3r/pyobfuscate.git 
python setup.py install
#-------------------------------------------------------------------------------
git clone https://github.com/nccgroup/metasploitavevasion.git 
#---------------------------------Make shortcut to OPT--------------------------
ln -s /opt /root/Desktop
#---------------------------------Get more goodys--------------------------
echo "Now to Download Nessus and cobalt strike"
iceweasel --new-tab https://www.tenable.com/products/nessus/select-your-operating-system https://www.cobaltstrike.com/download
#-------------------FIX FUCKING OPENVAS-----------------------------
#openvas-setup
#netstat -antp
#openvas-check-setup
#openvas-nvt-sync
#greenbone-nvt-sync
#openvas-mkcert
#openvas-mkcert-client -n -i
#openvasmd --create-user=root --role=Admin
#echo "ADD YOUR USER NAME BY ADDING INFO ON NEXT LINE AND UNCOMMENT"
#openvasmd --create-user=admin --new-password=admin
#openvasmd --user=admin --new-passwod=admin
#echo "Created OPENVAS User. UN=admin PW=admin"
#openvasmd --rebuild
#openvas-check-setup
#openvas-start
#-------------------FIX missing updates form installs and fix settings-----------------------------
apt-get update --fix-missing
apt-get -f install
apt-get install --reinstall gnome-control-center --fix-missing
#---------------------Setup and prep for metasploit------------------------------
/etc/init.d/postgresql start
msfdb init
echo "INSTALL VM TOOLS"
