#!/bin/bash
apt-get update && apt-get upgrade -y && apt-get dist-upgrade -y 
service metsploit start
service postgresql start
msfupdate
apt-get install geany -y 
apt-get install mitmf -y
apt-get install fruitywifi -y
apt-get install tor -y
apt-get install -f
service tor start
apt-get --force-yes install firefox-mozilla-build
